### ISSUE TITLE
Add Checkbox to Flip If/Else

### ISSUE THREAD

**Issue by benwilkerson** [morelup/Five9-Call-Flow-Addin-Issues#32]
The Position of the If/Else causes the flow to lay in a format not conducive to simplicity.  Create a checkbox to allow the if/else to be flipped.

**Comment by morelup** [comment]
![image](https://user-images.githubusercontent.com/8505256/68641337-7f18cc00-04d8-11ea-8a3a-1a24b7a1ac78.png)
