### ISSUE TITLE
Create Separate Shapes for a Campaign Transfer and Foreign Script Transfer

### ISSUE THREAD

**Issue by benwilkerson** [morelup/Five9-Call-Flow-Addin-Issues#33]
Create Separate Shapes for a Campaign Transfer and Foreign Script Transfer.  Can be difficult to interpret for engineers building as to which shape to utilize.

**Comment by morelup** [comment]
Campaign Transfers are performed by Agent Transfer nodes to the campaigns extension.  Possibly will add "Campaign" as an option the generic transfer

**Comment by morelup** [comment]
Yeah added to the Generic Transfer shape
