### ISSUE TITLE
Follow Up Needed Check Box

### ISSUE THREAD

**Issue by angmarceau1971** [morelup/Five9-Call-Flow-Addin-Issues#40]
Wondering if it would be possible to add the "Follow Up Needed" check box on the stencil objects that if checked it will turn the lettering red, or the shape red or something to indicate follow up is required on that object?   I can't color the boxes.  So somethign to be able to flag objects that need follow up would be nice.

**Comment by morelup** [comment]
Found some time so I added it as a text box, if the textbox is populated it flags the shape
