### ISSUE TITLE
GetDigits Module - Prompt Export

### ISSUE THREAD

**Issue by jppennin** [morelup/Five9-Call-Flow-Addin-Issues#46]
The Compile Automated Tables export fails to compile and prompt verbiage from GetDigit Modules.
![getdigits](https://user-images.githubusercontent.com/57263798/68035496-5ea37300-fc89-11e9-8755-7a2d6ec9e6dc.PNG)

**Comment by morelup** [comment]
Updated so any shape that has "Verbiage" and "Prompt" should be exporting to the prompt export tool.  Also fixed the generation of the prompt file doesn't break due to line returns.
