### ISSUE TITLE
Update Properties on Shape Drop

### ISSUE THREAD

**Issue by angmarceau1971** [morelup/Five9-Call-Flow-Addin-Issues#50]
Any way to restrict the Shape Details opening for only shapes that have Properties to complete?
Specifically Connector (Arrow)
![image](https://user-images.githubusercontent.com/48724436/69179274-4761e380-0ad9-11ea-9dea-e39d3416ed73.png)

**Comment by morelup** [comment]
Will look into fixing in february release.

**Comment by morelup** [comment]
Fixed v1.0.3
