### ISSUE TITLE
Generate TTS Prompt Issue

### ISSUE THREAD

**Issue by angmarceau1971** [morelup/Five9-Call-Flow-Addin-Issues#55]
The Description inputted is not uploading to VCC. Instead it's putting the text field.

Recreate:
**Click Generate TTS Prompt**
![image](https://user-images.githubusercontent.com/48724436/71997664-42cdc780-320c-11ea-8af2-fecfc1080917.png)

**Type in Prompt Name, Prompt Desc, Prompt Text**
![image](https://user-images.githubusercontent.com/48724436/71997737-62fd8680-320c-11ea-9d55-5428ce555218.png)

**Value that goes into description field is the Text and not the Description**
![image](https://user-images.githubusercontent.com/48724436/71997799-7e689180-320c-11ea-8917-e1975310ce31.png)

**Comment by morelup** [comment]
like 139 of ttsgenerator.cs 
pg.createTTSPromptsAndUpload(txtPromptName.Text,txtPromptDesc.Text,txtPromptText.Text,txtVCCLang.Text, _tempVoice.lang, _tempVoice.name, txtUsername.Text);   

txtPromptDesc.Text was originally "".  Need to test to confirm no issues, will be in 1.1.0 if tests are succesful

**Comment by morelup** [comment]
Yep was fixed in previous version marking as closed now.
