### ISSUE TITLE
Enhancement:  Add Parameters to the Schedule Container

### ISSUE THREAD

**Issue by angmarceau1971** [morelup/Five9-Call-Flow-Addin-Issues#61]
Add field to indicate parameters being passed in schedules.
![image](https://user-images.githubusercontent.com/48724436/72613221-fca7f080-38fc-11ea-83c2-baa7c1e83691.png)

**Comment by angmarceau1971** [comment]
Also add field for IVR Script being called

**Comment by morelup** [comment]
Adding the values to the shape (won't display until we come up with a better shape design)

**Comment by morelup** [comment]
in 1.1.0 release.  Added Parameters field to schedule shape.  IVR Script would be defined by Foreign Script node after Schedule Shape
